name: Update GitHub Profile Trophy

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

permissions:
  contents: write

jobs:
  trophy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout profile repository
        uses: actions/checkout@v4

      - name: Generate trophy
        uses: Priyanshav/github-profile-trophy@master
        with:
          username: Priyanshav
          output_path: trophy.svg
          token: ${{ secrets.TROPHY_TOKEN }}
          theme: tokyonight

      - name: Commit trophy
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add trophy.svg

          if git diff --cached --quiet; then
            echo "No trophy changes."
          else
            git commit -m "Update GitHub profile trophies"
            git push
          fi
